version: '3.5'
volumes:
    db:
services:
    db:
        build:
            context: db
        ports:
            - '5432:5432'
        volumes:
            - db:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: jbot
            POSTGRES_PASSWORD: jbot
