version: '3.5'
volumes:
    postgres_db:
services:
    postgres_db:
        build:
            context: postgres_db
        ports:
            - '5432:5432'
        volumes:
            - postgres_db:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: jbot
            POSTGRES_PASSWORD: jbot
