# To create symbolink links:
# Windows: mklink docker-compose.yml docker-compose.dev.yml
# Linux: ln -s docker-compose.dev.yml docker-compose.yml

version: "3.8"

networks:
  mongodb_network:

volumes:
  postgres-db-data:
  pgadmin-data:
  mongo-db-data:

services:
# ---------------------------------- Postgres composer ---------------------------------------------

  postgres-db:
    # Dockerfile to setup image and init pgdev/schema.sql
    build:
      context: postgres
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: tek
      POSTGRES_PASSWORD: tek

  pgadmin:
    image: dpage/pgadmin4:4.22
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "8090:80"
    # Hostname alias for the postgres-db service (so we don't need to know the ip)
    links:
      - "postgres-db:pgsql-server"
    environment:
      PGADMIN_DEFAULT_EMAIL: tekready-solutions@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123Stella!
      PGADMIN_LISTEN_PORT: 80

  # ----------------------------------- Mongo composer ---------------------------------------------

  mongo-db:
    image: mongo
    networks:
      - mongodb_network
    volumes:
      - mongo-db-data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo-db
    networks:
      - mongodb_network
    volumes:
      - mongo-db-data
    ports:
      - "8081:8081"
    restart: unless-stopped
    environment:
       # Mongo service
      - ME_CONFIG_MONGODB_SERVER=mongo-db
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass12345
        # Mongo Express web interface access
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123