spring:
    # Maven-Spring Profilo attivo
    profiles.active: @activeProfile@

    # Output colorato
    output.ansi.enabled: always

    # Cache busting per risorse statiche
    resources.chain.strategy.content:
        enabled: true
        paths: /**

    # Resource Bundle settings
    messages:
        cache-seconds: -1
        encoding: UTF-8

    # JPA settings
    jpa:
        # Jpa nelle view disattivato
        open-in-view: false
        properties:
            hibernate:
                current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
                # Workaround. Vedi:
                # https://github.com/pgjdbc/pgjdbc/issues/1102
                # https://hibernate.atlassian.net/browse/HHH-12368
                jdbc.lob.non_contextual_creation: true

        hibernate:
            naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    # Database settings
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: admin
        password: admin

    # H2 Settings
    h2.console:
        enabled: true
        settings:
            trace: false
            web-allow-others: false

logging:
    level:
        org.hibernate:
            tool.hbm2ddl: DEBUG
            SQL: DEBUG
            type: DEBUG
            type.EnumType: INFO
            type.BasicTypeRegistry: INFO
            descriptor:
                sql: DEBUG
                sql.BasicExtractor: DEBUG

security:
    # oauth2, basic (se mancante fallback a basic automaticamente)
    type: oauth2
    # Workaround. Vedi:
    # https://docs.spring.io/spring-security-oauth2-boot/docs/current/reference/htmlsingle/
    # 2.7.2 Changing the Filter Order
    oauth2:
        resource.filter-order: 3

        # ClientDetailsProperties
        client:
            clientId: jBotClientId
            clientSecret: jBotSecret
            resourceId: jBotResourceId
            authority: ROLE_CLIENT
            grants: password,refresh_token,client_credentials
            scope: read,write
            accessTokenValidity: 1800
            refreshTokenValidity: 3600


